# Exercise 9.3 (v)

In [4]:
import numpy as np

def problem9_3_5():
    #get initial probability distribution
    X0 = 1/6 * np.ones(6)
    #get power values
    power = 10**np.arange(0, 6)
    #define our transition matrix
    Q = np.array([[0, 1, 0.5, 0, 0, 0], 
                  [0, 0, 0, 0.5, 0, 0], 
                  [0, 0, 0, 0.5, 0, 0], 
                  [1, 0, 0,0, 0, 1], 
                  [0, 0, 0.5, 0, 0, 0], 
                  [0, 0, 0, 0, 1, 0]])
    
    #now we can print out our marginal distribution for each p in power
    for p in power:
        #print corresponding marginal distribution
        new_Q = np.linalg.matrix_power(Q, p)
        MD = np.linalg.matrix_power(Q, p) @ X0
        print('power = ' + str(p), MD, sep='\n')
        print()

    
    
problem9_3_5()

power = 1
[0.25       0.08333333 0.08333333 0.33333333 0.08333333 0.16666667]

power = 10
[0.27734375 0.14713542 0.14713542 0.26822917 0.09244792 0.06770833]

power = 100
[0.23076975 0.15384573 0.15384573 0.30769234 0.07692325 0.0769232 ]

power = 1000
[0.23076923 0.15384615 0.15384615 0.30769231 0.07692308 0.07692308]

power = 10000
[0.23076923 0.15384615 0.15384615 0.30769231 0.07692308 0.07692308]

power = 100000
[0.23076923 0.15384615 0.15384615 0.30769231 0.07692308 0.07692308]

